In [7]:
import numpy as np
import pandas as pd

In [8]:
from datetime import date,datetime
times = pd.date_range(end=date.today().strftime("%m-%d-%y"), periods=30)

In [3]:
df_times = pd.DataFrame(times)
df_times.head()

           0
0 2021-02-20
1 2021-02-21
2 2021-02-22
3 2021-02-23
4 2021-02-24

In [9]:
# Generating Last 30 days same as the name of the csv file present in the github

import datetime
df_times=[]
for i in times:
    formatted_date = datetime.date.strftime(i, "%m-%d-%Y")
    df_times.append(formatted_date)
print(df_times)

['02-20-2021', '02-21-2021', '02-22-2021', '02-23-2021', '02-24-2021', '02-25-2021', '02-26-2021', '02-27-2021', '02-28-2021', '03-01-2021', '03-02-2021', '03-03-2021', '03-04-2021', '03-05-2021', '03-06-2021', '03-07-2021', '03-08-2021', '03-09-2021', '03-10-2021', '03-11-2021', '03-12-2021', '03-13-2021', '03-14-2021', '03-15-2021', '03-16-2021', '03-17-2021', '03-18-2021', '03-19-2021', '03-20-2021', '03-21-2021']

In [10]:
df_list = [pd.DataFrame() for df in df_times]
df_dict = dict(zip(df_times, df_list))

In [25]:
df_dict.keys()

dict_keys(['02-20-2021', '02-21-2021', '02-22-2021', '02-23-2021', '02-24-2021', '02-25-2021', '02-26-2021', '02-27-2021', '02-28-2021', '03-01-2021', '03-02-2021', '03-03-2021', '03-04-2021', '03-05-2021', '03-06-2021', '03-07-2021', '03-08-2021', '03-09-2021', '03-10-2021', '03-11-2021', '03-12-2021', '03-13-2021', '03-14-2021', '03-15-2021', '03-16-2021', '03-17-2021', '03-18-2021', '03-19-2021', '03-20-2021', '03-21-2021'])

In [12]:
url_part = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/'

In [14]:
#Filtering the data for Hillsborough during read, so that we dont pull extra data 

df_final = pd.DataFrame()
Date = []
for i, (key, value) in enumerate(df_dict.items()):
    try:
        value = pd.read_csv(url_part+key+'.csv', iterator=True,error_bad_lines=False)
        #print('i ',i,'key ',key)        
        value = pd.concat([chunk[chunk['Combined_Key'] == 'Hillsborough, Florida, US'] for chunk in value])
        df_final = df_final.append(value)
        Date.append(key)
    except Exception:
        #print('Another Error!!', key+'.csv')
        continue

In [16]:
#Adding file date to the dataframe to keep track of the record pulled

df_final['FileDate'] = Date
df_final.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio,FileDate
1010,12057.0,Hillsborough,Florida,US,2021-02-21 05:24:33,27.927656,-82.320132,108648,1448,0.0,107200.0,"Hillsborough, Florida, US",7381.138720,1.332744,02-20-2021
1010,12057.0,Hillsborough,Florida,US,2021-02-22 05:24:21,27.927656,-82.320132,108964,1448,0.0,107516.0,"Hillsborough, Florida, US",7402.606578,1.328879,02-21-2021
1010,12057.0,Hillsborough,Florida,US,2021-02-23 05:23:41,27.927656,-82.320132,109174,1455,0.0,107719.0,"Hillsborough, Florida, US",7416.873193,1.332735,02-22-2021
1010,12057.0,Hillsborough,Florida,US,2021-02-24 05:29:16,27.927656,-82.320132,109527,1465,0.0,108062.0,"Hillsborough, Florida, US",7440.854692,1.337570,02-23-2021
1010,12057.0,Hillsborough,Florida,US,2021-02-25 05:24:57,27.927656,-82.320132,110086,1470,0.0,108616.0,"Hillsborough, Florida, US",7478.831062,1.335320,02-24-2021

In [20]:
df_final.reset_index(inplace=True)

In [21]:
df_final.drop('index', axis=1, inplace=True)
df_final.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio,FileDate
0,12057.0,Hillsborough,Florida,US,2021-02-21 05:24:33,27.927656,-82.320132,108648,1448,0.0,107200.0,"Hillsborough, Florida, US",7381.138720,1.332744,02-20-2021
1,12057.0,Hillsborough,Florida,US,2021-02-22 05:24:21,27.927656,-82.320132,108964,1448,0.0,107516.0,"Hillsborough, Florida, US",7402.606578,1.328879,02-21-2021
2,12057.0,Hillsborough,Florida,US,2021-02-23 05:23:41,27.927656,-82.320132,109174,1455,0.0,107719.0,"Hillsborough, Florida, US",7416.873193,1.332735,02-22-2021
3,12057.0,Hillsborough,Florida,US,2021-02-24 05:29:16,27.927656,-82.320132,109527,1465,0.0,108062.0,"Hillsborough, Florida, US",7440.854692,1.337570,02-23-2021
4,12057.0,Hillsborough,Florida,US,2021-02-25 05:24:57,27.927656,-82.320132,110086,1470,0.0,108616.0,"Hillsborough, Florida, US",7478.831062,1.335320,02-24-2021

In [22]:
df_final.to_excel('COVID-19 Daily Data.xls',index=False, sheet_name='Hillsborough')